[package]
name = "mere_memory_types"
version = "0.91.0"
authors = ["Matthew Brisebois <matthew.brisebois@holo.host>"]
edition = "2018"
license = "CAL-1.0"
repository = "https://github.com/spartan-holochain-counsel/hc-zome-mere-memory"
description = "A Holochain Zome for storing large or small byte values"
readme = "README.md"

[lib]
name = "mere_memory_types"
crate-type = ["cdylib", "rlib"]

[dependencies]
hdi = "0.3.7-rc.0"
serde = "1"

getrandom = { version = "=0.2.7", features = ["custom"] } # temporary fix for compile error in
                                                          # - v0.3.0-beta-dev.8
                                                          # - v0.2.1-beta-rc.0
                                                          # - v0.2.1
                                                          # - v0.2.2

[dev-dependencies]
holo_hash = { version = "0.2.6", features = ["encoding"] }
