[package]
name = "mere_memory_types"
version = "0.84.0"
authors = ["Matthew Brisebois <matthew.brisebois@holo.host>"]
edition = "2018"
license = "CAL-1.0"
repository = "https://github.com/mjbrisebois/hc-zome-mere-memory"
description = "A Holochain Zome for storing large or small byte values"
readme = "README.md"

[lib]
name = "mere_memory_types"
crate-type = ["cdylib", "rlib"]

[dependencies]
hdi = "0.2.3-beta-rc.0"
serde = "1"
sha2 = "0"
